### ISSUE TITLE
Pull changes from git.sukimashita.com branch

### ISSUE THREAD

**Issue by FunkyM** [Chronic-Dev/libirecovery#12]
As the title suggests. Branch lives here and mainly adds a proper build system and support for latest hardware:
http://cgit.sukimashita.com/libirecovery.git/

It appears there are a multitude of "libirecovery" forks all around the place and it might be feasable to coordinate this a bit, too.
No real release management either.

**Comment by Jaywalker** [comment]
Please review posixninja's libirecovery-2.0. It appears to be using an autotools system. his system is lacking limera1n support, although it appears to be in the source tree, but commented out. If your system can support that as well I'll merge your fork into this branch. You may also send a pull request to him.
