### ISSUE TITLE
MakeFile will not compile on Arch Linux

### ISSUE THREAD

**Issue by sirkingchase** [Chronic-Dev/libirecovery#13]
When trying to compile I get -
Cloning into '/tmp/yaourt-tmp-samarch/aur-libirecovery-git/src/libirecovery-build'...
done.
gcc -c libirecovery.c -o libirecovery.o -m32 -fPIC -O3 -I./include -I/usr/include -I/usr/local/include 
gcc -o libirecovery.so libirecovery.o -L/usr/lib -L/usr/local/lib -shared -W1,-soname,libirecovery.so -m32 -lusb-1.0
gcc: error: unrecognized command line option ‘-W1,-soname,libirecovery.so’
make: **\* [libirecovery.so] Error 1

Solution - 
I used an old Makefile from tokm's old fork and with some modification it worked.  I cloned the git into a directory and executed these commands -
gcc -o libirecovery.o -c libirecovery.c -g -I./include -lreadline -fPIC
gcc -o libirecovery.so libirecovery.o -g -shared -Wl,-soname,libirecovery.so -lusb-1.0
gcc -o irecovery irecovery.c -g -I./include -L. -lirecovery -lreadline

It successfully compiles and you get the executable, then you do -
cp libirecovery.so /usr/lib/libirecovery.so
cp include/libirecovery.h /usr/local/include/libirecovery.h
cp irecovery /usr/local/bin/irecovery
ldconfig

**Comment by winocm** [comment]
Well, that makes sense since -Wl isn't -W1.

**Comment by sirkingchase** [comment]
I didn't even realize that was the reason it didn't work.  Awesome.

This turned out to be a dead end anyways I couldn't get idevicerestore to compile.  Only thing Ievbeen able to use libirecovery for was to kick the iPhone out of a recovery loop
