### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by rdqronos** [Chronic-Dev/libirecovery#6]
I'm an idiot, yes.
I've downloaded this. I've run make on it. It created the libirecovery.a and libirecovery.o files. What do I do now? I'm on a Mac, with my terminal application being, well, Terminal, and I'm a total n00b. Any help at all? I just really wanna get this working...
TLDR, how in gods name do I do this

**Comment by markcoker** [comment]
You have to compile with no errors getting the binary file. This isnt really a program for people who dont know how to use terminal. http://theiphonewiki.com/wiki/index.php?title=IRecovery has the most information i can find. Good Luck

**Comment by electromaggot** [comment]
On Mac OS X...
Doing a "make irecovery" reveals that it's missing a library: usb-1.0
Find it here:  http://www.libusb.org/
Download that source, do a "configure" and "make all" and "make install".
The iRecovery makefile wants "/opt/local/lib" -- it's easiest just to "ln -s /usr/local /opt/local"
Then you should have an "irecovery" command line executable.

**Comment by boxingcow** [comment]
_Sighs_ If you cannot build this, then you probably do not need this... I think that is simple enough.

**Comment by Haifisch** [comment]
ikr i use my program called BootRa1n any one wanna beta?

**Comment by boxingcow** [comment]
This is not the place to advertise your own software...

**Comment by Haifisch** [comment]
im sorry....

**Comment by boxingcow** [comment]
Actually, I apologise, but there is about a 100000001 recovery GUIs - people aren't original enough, and I am always grumpy in the morning :P

**Comment by Haifisch** [comment]
No its cool mean Chronic-Dev deserves there own stuff here not mine. its just that i build all this that i make and im only 13

**Comment by boxingcow** [comment]
Might I suggest then that you leave GUIs and learn a real language... Once you know a real language or two go back to GUIs.

**Comment by Haifisch** [comment]
Well i know three languages HTML,CSS,C, and learning C++

**Comment by boxingcow** [comment]
Then put them to use - be creative, don't make GUIs for a program which already has 10000000 GUIs and is piss simple to use without GUIs anyway!

**Comment by Haifisch** [comment]
man i work for a month on this one program i needed to restore my Computer i backed everything up ont a flash drive but it burnt out or something so every thing is lost. But yeah i will.

**Comment by Haifisch** [comment]
Exception Type:  EXC_BAD_ACCESS (SIGBUS)
Exception Codes: KERN_PROTECTION_FAILURE at 0x0000000000000000

Any way to fix this?
Bus Error 10

**Comment by posixninja** [comment]
yes, quit trying to dereference a null value :-P

**Comment by Haifisch** [comment]
thanks posix i got it
