### ISSUE TITLE
irecovery won't show any output in terminal

### ISSUE THREAD

**Issue by ghost** [Chronic-Dev/libirecovery#7]
Hello, 

When I try to run:

root@desert:/home/marco/libirecovery# ./irecovery -s

> radio readnvram

i won't get any output on my terminal.

I am running the latest irecovery version (06/07/11) with an iPhone 3g - 4.1.2 on Ubuntu Linux 11.04.

**Comment by markcoker** [comment]
Are you sure iboot supports that command with  IOS 4.1.2?

**Comment by ghost** [comment]
Thank you.
I tried multiple devices on multiple computers, but none of them supported this command anymore.
